### ISSUE TITLE
Would you like to publish Peniko to crates.io?

### ISSUE THREAD

**Issue by pieterdd** [linebender/peniko#17]
Have you considered publishing Peniko to crates.io? Since crates.io does not support Git dependencies, publishing Peniko would enable crates that depend on Peniko to publish as well.

**Comment by raphlinus** [comment]
Absolutely, this will be part of the release process for Vello 0.1, which we hope to get out soon. We don't have a hard date to promise, however.

**Comment by PoignardAzur** [comment]
I'd like to hurry this process along, see https://github.com/linebender/vello/issues/302 for why.

What would it take to publish this?

**Comment by pieterdd** [comment]
Keep in mind that most opensource projects are maintained by volunteers as a passion project, not a job. In that sense, if it's of high importance to you that Peniko publishes to crates.io, it might be more effective to approach this from a perspective "can I help, and if so, how?".

**Comment by PoignardAzur** [comment]
Well seeing as I'm being paid to improve the developer experience of the Linebender ecosystem, this is a perspective I'm embracing, yes =)

**Comment by xorgy** [comment]
0.1.0 is released and published to crates.io
