### ISSUE TITLE
Brush, with alpha.

### ISSUE THREAD

**Issue by simbleau** [linebender/peniko#27]
In Velato, there's a section @dfrg wrote stating we should move logic to peniko to allow alpha factors for brushes.

```rust

// TODO: probably move this to peniko. The better option is to add an alpha
// parameter to the draw methods in vello. This is already handled at the
// encoding level.
pub(crate) fn brush_with_alpha(brush: &Brush, alpha: f64) -> Brush {
    if alpha == 1.0 {
        brush.clone()
    } else {
        match brush {
            Brush::Solid(color) => color.with_alpha_factor(alpha as f32).into(),
            Brush::Gradient(gradient) => Brush::Gradient(peniko::Gradient {
                kind: gradient.kind,
                extend: gradient.extend,
                stops: gradient
                    .stops
                    .iter()
                    .map(|stop| stop.with_alpha_factor(alpha as f32))
                    .collect(),
            }),
            _ => unreachable!(),
        }
    }
}

```

**Comment by ratmice** [comment]
Probably not going to get to this soon as i am sick :sneezing_face:.  When lifted into peniko the unreachable arm of the match statement isn't actually unreachable.  I guess first choice would be making it return a `Result` and failing that, switch `Brush::Image(_) => panic!("Unsupported brush variant `Image`"),` to at least give it a more useful error.

**Comment by waywardmonkeys** [comment]
I confess to being a little confused since the comment says this could also go into Vello and that being a better option?

**Comment by simbleau** [comment]
> I confess to being a little confused since the comment says this could also go into Vello and that being a better option?

@dfrg can you clarify your comment?

**Comment by dfrg** [comment]
Sure. The various brush methods in `Encoding` have support for applying an alpha modifier but this isn’t exposed by `Scene`. The parameter list is already quite long for the fill and stroke methods so I’m reluctant to tack on another one. Maybe this calls for a builder or an options parameter to capture the less frequently used properties. 

I still think this would be useful in peniko.

**Comment by dfrg** [comment]
Ah, I see the problem with the image brush. Seems like the best option there would be to add an alpha multiplier field to the image struct and then have vello (or other renderers) handle it.
