### ISSUE TITLE
I like the idea - do you want to protect main?

### ISSUE THREAD

**Issue by derekdreery** [linebender/peniko#3]
Just came to say that I think this is a cool project that solves a real problem - there have been a few times where I've wanted things like a Color type but don't want to pull in all of piet.

One note - I would at least disable rewriting history (force push) and delete on the main branch.

**Comment by dfrg** [comment]
I’m hoping this can be more generally useful. At the very least, my plan is to make use of this crate in parley to provide better integration with vello without taking a hard dependency. 

I think branch protection is now set up as you mentioned? Please feel free to double check.

**Comment by DJMcNab** [comment]
Confirmed that `main` has branch protection
