### ISSUE TITLE
Rename `with_alpha_factor`, add `set_alpha`?

### ISSUE THREAD

**Issue by waywardmonkeys** [linebender/peniko#51]
From @simbleau on https://github.com/linebender/interpoli/pull/2#discussion_r1720788697

> It would be nice to see a .set_alpha(alpha) added and rename .with_alpha_factor(alpha) to .multiply(alpha) or something

This was added as a breaking change since the last release and the suggestion now is to perhaps modify that in a breaking way, so I'd like this to be resolved before we do the impending release.

Related:

* #27
* #40 
* #43 

cc: @simbleau @dfrg

**Comment by simbleau** [comment]
I would guess (1): overwrite the alpha of each stop with the given value.

I would call 3/4 a method named "multiply" or something different.

**Comment by DJMcNab** [comment]
I've done the breaking part of this in #52 to unblock this issue. A new `set_alpha` can be added separately.

If `set_alpha` is needed, I'd prefer it to be external due to the muddy semantics when gradients have different colour modes. Either way, if #52 lands, that should unblock a release.
